### ISSUE TITLE
Support utf-8 encoding in zip name

### ISSUE THREAD

**Issue by vtexier** [wamania/ZipStreamedResponseBundle#2]
Hello,

I need UTF-8 support in the Zip name, as Symfony support it.

So I have made a quick patch to support it.

[commit-84e4e55.txt](https://github.com/wamania/ZipStreamedResponseBundle/files/533217/commit-84e4e55.txt)

Could you include this patch ?

Thanks for your work !

**Comment by wamania** [comment]
Done
Thank you for your patch
